### ISSUE TITLE
'Desktop/a.bib' does not appear to be a file, so autocomplete-bibtex will not try to parse it.

### ISSUE THREAD

**Issue by TianyiShi2001** [apcshields/autocomplete-bibtex#103]
'Desktop/a.bib' does not appear to be a file, so autocomplete-bibtex will not try to parse it.

**Comment by TianyiShi2001** [comment]
How can I troubleshoot this problem? Thanks.

**Comment by apcshields** [comment]
It looks like you need to give the full file path to your .bib file.

A

**Comment by TianyiShi2001** [comment]
I tried 

> Macintosh HD⁩/Users⁩⁨/tianyishi⁩⁨/⁩Desktop/a.bib

and

> ‎⁨Users⁩⁨/tianyishi⁩⁨/⁩Desktop/a.bib
and

> tianyishi⁩⁨/⁩Desktop/a.bib
and it's still not working.

My MacOS is 10.14.2 Beta and my Atom and the autocomplete-latex package is up to date.

My .bib file looks like this:
`@article{RN34,
   author = {Tahmasebi, S. and Khoutorsky, A. and Mathews, M. B. and Sonenberg, N.},
   title = {Translation deregulation in human disease},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {12},
   pages = {791-807},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/s41580-018-0034-x},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/30038383},
   year = {2018},
   type = {Journal Article}
}

@article{RN32,
   author = {Skvortsova, K. and Iovino, N. and Bogdanovic, O.},
   title = {Functions and mechanisms of epigenetic inheritance in animals},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {12},
   pages = {774-790},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/s41580-018-0074-2},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/30425324},
   year = {2018},
   type = {Journal Article}
}

@article{RN30,
   author = {Schuller, A. P. and Green, R.},
   title = {Roadblocks and resolutions in eukaryotic translation},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {8},
   pages = {526-541},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/s41580-018-0011-4},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/29760421},
   year = {2018},
   type = {Journal Article}
}

@article{RN29,
   author = {Rousseau, A. and Bertolotti, A.},
   title = {Regulation of proteasome assembly and activity in health and disease},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {11},
   pages = {697-712},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/s41580-018-0040-z},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/30065390},
   year = {2018},
   type = {Journal Article}
}

@article{RN31,
   author = {Leppek, K. and Das, R. and Barna, M.},
   title = {Functional 5' UTR mRNA structures in eukaryotic translation regulation and how to find them},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {3},
   pages = {158-174},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/nrm.2017.103},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/29165424},
   year = {2018},
   type = {Journal Article}
}

@book{RN37,
   author = {Krebs, Jocelyn E. and Goldstein, Elliott S.  and Kilpatrick, Stephen T.},
   title = {Lewin’s genes XII},
   publisher = {Jones & Bartlett Learning },
   address = {Burlington, Massachusetts},
   edition = {12},
   ISBN = {9781284104493},
   year = {2018},
   type = {Book}
}

@book{RN39,
   author = {Hartwell, Leland and Goldberg, Michael L and Fischer, Janice A and Hood, Leroy},
   title = {Genetics: from genes to genomes},
   publisher = {McGraw-Hill Education},
   address = {New York, NY},
   edition = {6},
   ISBN = {9781259700903},
   url = {https://lccn.loc.gov/2017017175},
   year = {2018},
   type = {Book}
}

@book{RN42,
   author = {Hardin, Jeff and Bertoni, Gregory},
   title = {Becker’s World of the Cell},
   publisher = {Pearson Education Limited},
   address = {Essex CM20 2JE 
England},
   ISBN = {978-1-292-17769-4},
   year = {2018},
   type = {Book}
}

@article{RN33,
   author = {Hanson, G. and Coller, J.},
   title = {Codon optimality, bias and usage in translation and mRNA decay},
   journal = {Nat Rev Mol Cell Biol},
   volume = {19},
   number = {1},
   pages = {20-30},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/nrm.2017.91},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/29018283},
   year = {2018},
   type = {Journal Article}
}

@book{RN20,
   author = {Nelson, David L. and Cox, Michael M.},
   title = {Lehninger principles of biochemistry},
   publisher = {W. H. Freeman},
   edition = {7},
   ISBN = {9781319108243},
   url = {https://search.library.wisc.edu/catalog/999964334502121},
   year = {2017},
   type = {Book}
}

@article{RN17,
   author = {Theocharis, Achilleas D and Skandalis, Spyros S and Gialeli, Chrysostomi and Karamanos, Nikos K},
   title = {Extracellular matrix structure},
   journal = {Advanced drug delivery reviews},
   volume = {97},
   pages = {4-27},
   ISSN = {0169-409X},
   year = {2016},
   type = {Journal Article}
}

@book{RN14,
   author = {Murphy, Kenneth and Weaver, Casey},
   title = {Janeway's immunobiology},
   publisher = {Garland Science},
   address = {New York, NY},
   edition = {9},
   ISBN = {978-0-8153-4505-3},
   year = {2016},
   type = {Book}
}

@book{RN8,
   author = {Lodish, Harvey F. and Berk, Arnold and Kaiser, Chris and Krieger, Monty and Bretscher, Anthony and Ploegh, Hidde L. and Amon, Angelika  and Martin, Kelsey C},
   title = {Molecular cell biology},
   publisher = {W.H. Freeman},
   address = {New York},
   edition = {8},
   year = {2016},
   type = {Book}
}

@book{RN43,
   author = {Iwasa, Janet and Marshall, Wallace},
   title = {Karp’s Cell and Molecular Biology: Concepts and Experiments},
   publisher = {John Wiley & Sons},
   edition = {8},
   ISBN = {978‐1‐118‐88614‐4},
   year = {2016},
   type = {Book}
}

@article{RN26,
   author = {Bernardino de la Serna, J. and Schutz, G. J. and Eggeling, C. and Cebecauer, M.},
   title = {There Is No Simple Model of the Plasma Membrane Organization},
   journal = {Front Cell Dev Biol},
   volume = {4},
   pages = {106},
   ISSN = {2296-634X (Print)
2296-634X (Linking)},
   DOI = {10.3389/fcell.2016.00106},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/27747212},
   year = {2016},
   type = {Journal Article}
}

@book{RN19,
   author = {Bhagavan, N.V. and Chung-Eun, Ha},
   title = {Essentials of Medical Biochemistry with Clinical Cases},
   publisher = {Academic Press},
   edition = {2},
   year = {2015},
   type = {Book}
}

@book{RN22,
   author = {Berg, Jeremy M.; Tymoczko, John L.; Gatto Jr., Gregory J.; Stryer, Lubert},
   title = {Biochemistry},
   publisher = {W. H. Freeman},
   edition = {8},
   ISBN = {9781464126109},
   year = {2015},
   type = {Book}
}

@book{RN9,
   author = {Abbas, Abul K. and Lichtman, Andrew H. and Pillai, Shiv},
   title = {Cellular and molecular immunology},
   publisher = {Saunders},
   address = {Philadelphia, PA},
   edition = {8},
   ISBN = {978-0-323-22275-4},
   year = {2015},
   type = {Book}
}

@book{RN7,
   author = {Alberts, Bruce and Johnson, Alexander and Lewis, Julian and Morgan, David and Raff, Martin and Roberts, Keith and Walter, Peter},
   title = {Molecular biology of the cell},
   publisher = {Garland Science},
   edition = {6},
   ISBN = {978-0815345244},
   year = {2014},
   type = {Book}
}

@book{RN18,
   author = {Shier, David and Butler, Jackie and Lewis, Ricki},
   title = {Hole’s Human Anatomy & Physiology},
   publisher = {McGraw-Hill},
   edition = {12},
   pages = {1043},
   year = {2013},
   type = {Book}
}

@book{RN15,
   author = {Owen, Judith A. and Punt, Jenni and Stranford, Sharon A.},
   title = {Kuby Immunology },
   publisher = {W. H. Freeman and Company},
   address = {New York, NY},
   edition = {7},
   ISBN = {978-14292-1919-8},
   year = {2013},
   type = {Book}
}

@article{RN28,
   author = {Jouhet, J.},
   title = {Importance of the hexagonal lipid phase in biological membrane organization},
   journal = {Front Plant Sci},
   volume = {4},
   pages = {494},
   ISSN = {1664-462X (Print)
1664-462X (Linking)},
   DOI = {10.3389/fpls.2013.00494},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/24348497},
   year = {2013},
   type = {Journal Article}
}

@book{RN44,
   author = {Weaver, Robert F.},
   title = {Molecular biology},
   publisher = {McGraw-Hill},
   address = {New York, NY},
   edition = {5},
   ISBN = {978-0-07-352532-7},
   year = {2012},
   type = {Book}
}

@book{RN11,
   author = {Proetzel, Gabriele and Ebersbach, Hilmar},
   title = {Antibody Methods and Protocols},
   publisher = {Humana Press},
   volume = {901},
   series = {Methods in Molecular Biology},
   ISBN = {978-1-61779-930-3},
   DOI = {10.1007/978-1-61779-931-0},
   year = {2012},
   type = {Book}
}

@article{RN12,
   author = {Mahmood, Tahrin and Yang, Ping-Chang},
   title = {Western blot: technique, theory, and trouble shooting},
   journal = {North American journal of medical sciences},
   volume = {4},
   number = {9},
   pages = {429},
   year = {2012},
   type = {Journal Article}
}

@book{RN21,
   author = {Voet, Donald. and Voet, Judith G.},
   title = {Biochemistry},
   publisher = {Wiley},
   edition = {4},
   year = {2011},
   type = {Book}
}

@article{RN24,
   author = {Simons, K. and Sampaio, J. L.},
   title = {Membrane organization and lipid rafts},
   journal = {Cold Spring Harb Perspect Biol},
   volume = {3},
   number = {10},
   pages = {a004697},
   ISSN = {1943-0264 (Electronic)
1943-0264 (Linking)},
   DOI = {10.1101/cshperspect.a004697},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/21628426},
   year = {2011},
   type = {Journal Article}
}

@book{RN38,
   author = {Strachan, Tom and Andrew, Read},
   title = {Human Molecular Genetics},
   publisher = {Garland Science},
   address = {New York},
   edition = {4},
   ISBN = {9780815341499},
   year = {2010},
   type = {Book}
}

@article{RN16,
   author = {Frantz, Christian and Stewart, Kathleen M. and Weaver, Valerie M.},
   title = {The extracellular matrix at a glance},
   journal = {J Cell Sci},
   volume = {123},
   number = {24},
   pages = {4195-4200},
   DOI = {10.1242/jcs.023820},
   url = {http://jcs.biologists.org/content/joces/123/24/4195.full.pdf},
   year = {2010},
   type = {Journal Article}
}

@article{RN25,
   author = {van Meer, G. and Voelker, D. R. and Feigenson, G. W.},
   title = {Membrane lipids: where they are and how they behave},
   journal = {Nat Rev Mol Cell Biol},
   volume = {9},
   number = {2},
   pages = {112-24},
   ISSN = {1471-0080 (Electronic)
1471-0072 (Linking)},
   DOI = {10.1038/nrm2330},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/18216768},
   year = {2008},
   type = {Journal Article}
}

@article{RN60,
   author = {Bonini, Nancy M.},
   title = {A Tribute to Seymour Benzer, 1921–2007},
   journal = {Genetics},
   volume = {180},
   pages = {1265-1273},
   year = {2008},
   type = {Journal Article}
}

@book{RN45,
   author = {Whitford, David},
   title = {Proteins: Structure and Function },
   publisher = {John Wiley & Sons},
   address = {Sussex, England},
   ISBN = {0-471-49893-9},
   year = {2005},
   type = {Book}
}

@book{RN41,
   author = {Latchman, David S.},
   title = {Gene regulation: a eukaryotic perspective},
   publisher = {Taylor & Francis Group},
   address = {New York, NY},
   edition = {5},
   ISBN = {0-203-01633-5},
   year = {2005},
   type = {Book}
}

@article{RN69,
   author = {Jacob, François and Perrin, David and Sánchez, Carmen and Monod, Jacques},
   title = {L'opéron : groupe de gènes à expression coordonnée par un opérateur [C. R. Acad. Sci. Paris 250 (1960) 1727–1729]},
   journal = {Comptes Rendus Biologies},
   volume = {328},
   number = {6},
   pages = {514-520},
   ISSN = {1631-0691},
   DOI = {https://doi.org/10.1016/j.crvi.2005.04.005},
   url = {http://www.sciencedirect.com/science/article/pii/S1631069105000673},
   year = {2005},
   type = {Journal Article}
}

@book{RN46,
   author = {Salway, J.G.},
   title = {Metabolism at a Glance },
   publisher = {Blackwell Publishing Ltd},
   address = {Oxford, United Kingdom },
   edition = {3},
   ISBN = {978-1-4051-0716-7},
   year = {2004},
   type = {Book}
}

@article{RN72,
   author = {Bertani, Giuseppe},
   title = {Lysogeny at Mid-Twentieth Century: P1, P2, and Other Experimental Systems},
   journal = {Journal of Bacteriology},
   volume = {186},
   number = {3},
   pages = {595},
   url = {http://jb.asm.org/content/186/3/595.abstract},
   year = {2004},
   type = {Journal Article}
}

@article{RN76,
   author = {Schleif, Robert},
   title = {AraC protein: A love–hate relationship},
   journal = {BioEssays},
   volume = {25},
   number = {3},
   pages = {274-282},
   ISSN = {0265-9247},
   DOI = {10.1002/bies.10237},
   url = {https://doi.org/10.1002/bies.10237},
   year = {2003},
   type = {Journal Article}
}

@book{RN10,
   author = {Burmester, Gerd-Rüdiger and Pezzutto, Antonio},
   title = {Color Atlas of Immunology},
   publisher = {Thieme},
   address = {Stuttgart, Germany},
   ISBN = {0-86577-964-3},
   year = {2003},
   type = {Book}
}

@article{RN65,
   author = {Stahl, F W},
   title = {The amber mutants of phage T4.},
   journal = {Genetics},
   volume = {141},
   pages = {439-442},
   year = {1995},
   type = {Journal Article}
}

@article{RN4,
   author = {Darst, Seth A. and Kubalek, Elizabeth W. and Kornberg, Roger D.},
   title = {Three-dimensional structure of Escherichia coli RNA polymerase holoenzyme determined by electron crystallography},
   journal = {Nature},
   volume = {340},
   pages = {730},
   DOI = {10.1038/340730a0},
   url = {http://dx.doi.org/10.1038/340730a0},
   year = {1989},
   type = {Journal Article}
}

@article{RN13,
   author = {Payne, William J and Marshall, DL and Shockley, RK and Martin, WJ },
   title = {Clinical laboratory applications of monoclonal antibodies},
   journal = {Clinical microbiology reviews},
   volume = {1},
   number = {3},
   pages = {313-329},
   ISSN = {0893-8512},
   year = {1988},
   type = {Journal Article}
}

@article{RN6,
   author = {Johnsrud, Lorraine},
   title = {Contacts between Escherichia coli RNA polymerase and a lac operon promoter},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {75},
   number = {11},
   pages = {5314-5318},
   ISSN = {0027-8424},
   year = {1978},
   type = {Journal Article}
}

@article{RN5,
   author = {Pribnow, D.},
   title = {Nucleotide sequence of an RNA polymerase binding site at an early T7 promoter},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {72},
   number = {3},
   pages = {784-788},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/1093168
https://www.ncbi.nlm.nih.gov/pmc/PMC432404/
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC432404/pdf/pnas00046-0014.pdf},
   year = {1975},
   type = {Journal Article}
}

@article{RN74,
   author = {Eisen, H. and Brachet, P. and Pereira da Silva, L. and Jacob, F.},
   title = {Regulation of repressor expression in lambda},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {66},
   number = {3},
   pages = {855-862},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/5269249
https://www.ncbi.nlm.nih.gov/pmc/PMC283129/},
   year = {1970},
   type = {Journal Article}
}

@article{RN2,
   author = {Crick, Francis },
   title = {Central dogma of molecular biology},
   journal = {Nature},
   volume = {227},
   number = {5258},
   pages = {561},
   ISSN = {1476-4687},
   year = {1970},
   type = {Journal Article}
}

@article{RN66,
   author = {Edgar, R. S. and Wood, W. B.},
   title = {Morphogenesis of bacteriophage T4 in extracts of mutant-infected cells},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {55},
   number = {3},
   pages = {498-505},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/5221234
https://www.ncbi.nlm.nih.gov/pmc/PMC224177/},
   year = {1966},
   type = {Journal Article}
}

@article{RN75,
   author = {Englesberg, Ellis and Irr, Joseph and Power, Joseph and Lee, Nancy},
   title = {Positive Control of Enzyme Synthesis by Gene C in the L-Arabinose System},
   journal = {Journal of Bacteriology},
   volume = {90},
   number = {4},
   pages = {946},
   url = {http://jb.asm.org/content/90/4/946.abstract},
   year = {1965},
   type = {Journal Article}
}

@article{RN64,
   author = {Brenner, S. and Stretton, A. O. W. and Kaplan, S.},
   title = {Genetic Code: The ‘Nonsense’ Triplets for Chain Termination and their Suppression},
   journal = {Nature},
   volume = {206},
   pages = {994},
   DOI = {10.1038/206994a0},
   url = {https://doi.org/10.1038/206994a0},
   year = {1965},
   type = {Journal Article}
}

@article{RN61,
   author = {Champe, Sewell P. and Benzer, Seymour},
   title = {An active cistron fragment},
   journal = {Journal of Molecular Biology},
   volume = {4},
   number = {4},
   pages = {288-292},
   ISSN = {0022-2836},
   DOI = {https://doi.org/10.1016/S0022-2836(62)80006-0},
   url = {http://www.sciencedirect.com/science/article/pii/S0022283662800060},
   year = {1962},
   type = {Journal Article}
}

@article{RN63,
   author = {Benzer, Seymour and Champe, Sewell P.},
   title = {A CHANGE FROM NONSENSE TO SENSE IN THE GENETIC CODE},
   journal = {Proceedings of the National Academy of Sciences},
   volume = {48},
   pages = {1114-1121},
   year = {1962},
   type = {Journal Article}
}

@article{RN70,
   author = {Jacob, François and Monod, Jacques},
   title = {Genetic regulatory mechanisms in the synthesis of proteins},
   journal = {Journal of Molecular Biology},
   volume = {3},
   number = {3},
   pages = {318-356},
   ISSN = {0022-2836},
   DOI = {https://doi.org/10.1016/S0022-2836(61)80072-7},
   url = {http://www.sciencedirect.com/science/article/pii/S0022283661800727},
   year = {1961},
   type = {Journal Article}
}

@article{RN62,
   author = {Crick, F. H. C. and Barnett, Leslie and Brenner, S. and Watts-Tobin, R. J.},
   title = {General Nature of the Genetic Code for Proteins},
   journal = {Nature},
   volume = {192},
   pages = {1227},
   DOI = {10.1038/1921227a0},
   url = {https://doi.org/10.1038/1921227a0},
   year = {1961},
   type = {Journal Article}
}

@article{RN57,
   author = {Benzer, S.},
   title = {ON THE TOPOGRAPHY OF THE GENETIC FINE STRUCTURE},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {47},
   number = {3},
   pages = {403-415},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/16590840
https://www.ncbi.nlm.nih.gov/pmc/PMC221592/},
   year = {1961},
   type = {Journal Article}
}

@article{RN68,
   author = {Pardee, Arthur B. and Jacob, François and Monod, Jacques},
   title = {The genetic control and cytoplasmic expression of “Inducibility” in the synthesis of β-galactosidase by E. coli},
   journal = {Journal of Molecular Biology},
   volume = {1},
   number = {2},
   pages = {165-178},
   ISSN = {0022-2836},
   DOI = {https://doi.org/10.1016/S0022-2836(59)80045-0},
   url = {http://www.sciencedirect.com/science/article/pii/S0022283659800450},
   year = {1959},
   type = {Journal Article}
}

@article{RN59,
   author = {Benzer, S.},
   title = {ON THE TOPOLOGY OF THE GENETIC FINE STRUCTURE},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {45},
   number = {11},
   pages = {1607-1620},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/16590553
https://www.ncbi.nlm.nih.gov/pmc/PMC222769/},
   year = {1959},
   type = {Journal Article}
}

@article{RN73,
   author = {Kaiser, Armin D.},
   title = {Mutations in a temperate bacteriophage affecting its ability to lysogenize Escherichia coli},
   journal = {Virology},
   volume = {3},
   number = {1},
   pages = {42-61},
   ISSN = {0042-6822},
   DOI = {https://doi.org/10.1016/0042-6822(57)90022-3},
   url = {http://www.sciencedirect.com/science/article/pii/0042682257900223},
   year = {1957},
   type = {Journal Article}
}

@article{RN58,
   author = {Benzer, S.},
   title = {FINE STRUCTURE OF A GENETIC REGION IN BACTERIOPHAGE},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {41},
   number = {6},
   pages = {344-354},
   ISSN = {0027-8424
1091-6490},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/16589677
https://www.ncbi.nlm.nih.gov/pmc/PMC528093/},
   year = {1955},
   type = {Journal Article}
}

@article{RN56,
   author = {Watson, J. D. and Crick, Francis. H. C.},
   title = {Molecular Structure of Nucleic Acids: A Structure for Deoxyribose Nucleic Acid},
   journal = {Nature},
   volume = {171},
   pages = {737},
   DOI = {10.1038/171737a0},
   url = {https://doi.org/10.1038/171737a0},
   year = {1953},
   type = {Journal Article}
}

@article{RN71,
   author = {Bertani, G.},
   title = {STUDIES ON LYSOGENESIS I},
   journal = {Journal of Bacteriology},
   volume = {62},
   number = {3},
   pages = {293},
   url = {http://jb.asm.org/content/62/3/293.abstract},
   year = {1951},
   type = {Journal Article}
}

@article{RN67,
   author = {Tatum, E. L. and Lederberg, J.},
   title = {Gene Recombination in the Bacterium Escherichia coli},
   journal = {Journal of bacteriology},
   volume = {53},
   number = {6},
   pages = {673-684},
   ISSN = {0021-9193
1098-5530},
   url = {https://www.ncbi.nlm.nih.gov/pubmed/16561324
https://www.ncbi.nlm.nih.gov/pmc/PMC518375/},
   year = {1947},
   type = {Journal Article}
}

@article{RN54,
   author = {Avery, Oswald T. and MacLeod, Colin M. and McCarty, Maclyn},
   title = {STUDIES ON THE CHEMICAL NATURE OF THE SUBSTANCE INDUCING TRANSFORMATION OF PNEUMOCOCCAL TYPES},
   journal = {The Journal of Experimental Medicine},
   volume = {79},
   pages = {137-158},
   year = {1944},
   type = {Journal Article}
}

@article{RN55,
   author = {Luria, S. E. and Delbrück, M.},
   title = {MUTATIONS OF BACTERIA FROM VIRUS SENSITIVITY TO VIRUS RESISTANCE},
   journal = {Genetics},
   volume = {28},
   pages = {491-511},
   year = {1943},
   type = {Journal Article}
}

@article{RN52,
   author = {Beadle, G. W. and Tatum, E. L.},
   title = {Genetic Control of Biochemical Reactions in Neurospora},
   journal = {Proceedings of the National Academy of Sciences of the United States of America},
   volume = {27},
   number = {11},
   pages = {499-506},
   DOI = {10.1073/pnas.27.11.499},
   url = {http://www.pnas.org/content/pnas/27/11/499.full.pdf},
   year = {1941},
   type = {Journal Article}
}

@article{RN50,
   author = {Garrod, Archibald E. },
   title = {The incidence of alkaptonuria: a study in chemical individuality},
   journal = {The Lancet},
   volume = {160},
   number = {4137},
   pages = {1616-1620},
   ISSN = {0140-6736},
   year = {1902},
   type = {Journal Article}
}

`

**Comment by apcshields** [comment]
It looks to me like you’re missing an initial /. I’d try (including the quotation marks):

"/Macintosh HD⁩/Users⁩⁨/tianyishi⁩⁨/⁩Desktop/a.bib"

A

**Comment by jadolan** [comment]
I got the same error on Windows when entering the path with quotation marks. Leaving out the quotation marks worked for me.

**Comment by apcshields** [comment]
Yes, sorry. The suggestion about the quotation marks was specific to Mac OS.

A
