### ISSUE TITLE
autocomplete not working

### ISSUE THREAD

**Issue by maxheld83** [apcshields/autocomplete-bibtex#13]
I've followed the instructions in the readme, set my path for the bibtex in the preferences pane `/Users/Max/Github/held-library/klein.bib`, and also set the file blacklist for autocomplete-plus accordingly.

But hitting `@something` in an `md`(or any other file type), I can't seem to get an autocompletion.

Any ideas how I might troubleshoot this issue?

Thanks so much for this great package!

**Comment by apcshields** [comment]
Maximilian,

Thanks. :)

Please try opening the developer tools (View > Developer > Toggle Developer Tools). If there’s anything printed in the Console, please send it to me.

Also, what operating system are you running?

Andrew

**Comment by maxheld83** [comment]
thanks, @apcshields should have thought of that.

I'm running `OS X 10.10.2` and `Atom 0.182.0`.

There *is* something in the dev console:

```
/Applications/Atom.app/Contents/Resources/app/src/package.js:241 Failed to activate package named 'autocomplete-bibtex' TypeError: Cannot read property 'length' of undefined
    at BibtexProvider.module.exports.BibtexProvider.buildWordList (/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:94:31)
    at BibtexProvider.buildWordList (/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:3:61)
    at new BibtexProvider (/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:37:12)
    at Object.module.exports.activate (/Users/Max/.atom/packages/autocomplete-bibtex/lib/main.coffee:13:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:235:27)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:464:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:445:29
```

**Comment by apcshields** [comment]
Maximilian,

I've tweaked a few things and released a new version, 0.5.3. Please update to that version, restart Atom, and let me know if the output in the developer console changes.

Thanks!
Andrew

**Comment by maxheld83** [comment]
wow thanks @apcshields that was fast.
It's still not working, unfortunately.
Autocomplete Plus works fine, just no @something completes.

Here's the error messages from the dev pane:

```
Error: ENOENT, no such file or directory 'U'code: "ENOENT"errno: -2message: "ENOENT, no such file or directory 'U'"path: "U"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }syscall: "stat"__proto__: d/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:131 module.exports.BibtexProvider.readBibtexFiles
/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:131 Error: ENOENT, no such file or directory 'U'code: "ENOENT"errno: -2message: "ENOENT, no such file or directory 'U'"path: "U"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }syscall: "stat"__proto__: d/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:131 module.exports.BibtexProvider.readBibtexFiles
/Users/Max/.atom/packages/Repl/lib/Repl.coffee:13 activate
index.js:57 Window load time: 2469ms
3/Applications/Atom.app/Contents/Resources/app/src/styles-element.js:175 Upgraded the following syntax theme selectors in `/Users/Max/.atom/packages/monokai-extended/index.less` for shadow DOM compatibility:

`.editor, .editor .gutter` => `:host, :host .gutter`
`.editor.is-focused .cursor` => `:host(.is-focused) .cursor`
`.editor.is-focused .selection .region` => `:host(.is-focused) .selection .region`
`.editor.is-focused .line-number.cursor-line-no-selection, .editor.is-focused .line.cursor-line` => `:host(.is-focused) .line-number.cursor-line-no-selection, :host(.is-focused) .line.cursor-line`
`.editor .gutter .line-number.git-line-added, .editor .gutter .line-number.git-line-modified, .editor .gutter .line-number.git-line-removed` => `:host .gutter .line-number.git-line-added, :host .gutter .line-number.git-line-modified, :host .gutter .line-number.git-line-removed`

See the upgrade guide for information on removing this warning.
10/Applications/Atom.app/Contents/Resources/app/src/styles-element.js:175 Upgraded the following syntax theme selectors in `/Users/Max/.atom/packages/monokai-extended/index.less` for shadow DOM compatibility:

`.editor, .editor .gutter` => `:host, :host .gutter`
`.editor.is-focused .cursor` => `:host(.is-focused) .cursor`
`.editor.is-focused .selection .region` => `:host(.is-focused) .selection .region`
`.editor.is-focused .line-number.cursor-line-no-selection, .editor.is-focused .line.cursor-line` => `:host(.is-focused) .line-number.cursor-line-no-selection, :host(.is-focused) .line.cursor-line`
`.editor .gutter .line-number.git-line-added, .editor .gutter .line-number.git-line-modified, .editor .gutter .line-number.git-line-removed` => `:host .gutter .line-number.git-line-added, :host .gutter .line-number.git-line-modified, :host .gutter .line-number.git-line-removed`

See the upgrade guide for information on removing this warning.
/Applications/Atom.app/Contents/Resources/app/src/styles-element.js:175 Upgraded the following syntax theme selectors in `/Users/Max/.atom/packages/monokai-extended/index.less` for shadow DOM compatibility:

`.editor, .editor .gutter` => `:host, :host .gutter`
`.editor.is-focused .cursor` => `:host(.is-focused) .cursor`
`.editor.is-focused .selection .region` => `:host(.is-focused) .selection .region`
`.editor.is-focused .line-number.cursor-line-no-selection, .editor.is-focused .line.cursor-line` => `:host(.is-focused) .line-number.cursor-line-no-selection, :host(.is-focused) .line.cursor-line`
`.editor .gutter .line-number.git-line-added, .editor .gutter .line-number.git-line-modified, .editor .gutter .line-number.git-line-removed` => `:host .gutter .line-number.git-line-added, :host .gutter .line-number.git-line-modified, :host .gutter .line-number.git-line-removed`

See the upgrade guide for information on removing this warning.
/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:125 '/' does not appear to be a file, so autocomplete-bibtex will not try to parse it.
/Users/Max/.atom/packages/autocomplete-bibtex/lib/provider.coffee:131 Error: ENOENT, no such file or directory 'U' {errno: -2, code: "ENOENT", path: "U", syscall: "stat", stack: (...)…}code: "ENOENT"errno: -2message: "ENOENT, no such file or directory 'U'"path: "U"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }syscall: "stat"__proto__: d
```

**Comment by apcshields** [comment]
Maximilian,

I think I’ve got it.

Open your config file (Atom > Open Your Config), scroll down to the autocomplete-bibtex section, and make sure that it looks something like this:

```
"autocomplete-bibtex":
    bibtex: [
      "/Users/aps/Documents/zotero.bib”
    ]
```

Not like this:

```
"autocomplete-bibtex":
    bibtex: "/Users/aps/Documents/zotero.bib”
```

(Which is to say, make sure that the file path to your BibTeX file is surrounded by brackets as well as quotes—it should be a JSON array.)

This afternoon, I’ll try to push an update that fixes that automatically.

Hope this works!
Andrew

**Comment by tpoisot** [comment]
Yep, that solves #12 too. **THANKS**! (for the solution and the package)

**Comment by maxheld83** [comment]
Darn, it's still not working for me ...

```
  "autocomplete-bibtex":
    bibtex: [
      "/Users/Max/Github/held-library/klein.bib"
    ]
  "autocomplete-plus":
    fileBlacklist: [
      ".*"
    ]
```

The error consoles is now ok, though, so I am guessing this is my stupidity or an isolated problem.

**Comment by tpoisot** [comment]
Have you reloaded after updating the config file?

**Comment by maxheld83** [comment]
yes, I've restarted Atom a couple of times over. Thanks though.

**Comment by cddesja** [comment]
My issue is perhaps related to this. I am also on OS X 10.10.2 running 0.187.0 with autocomplete-bibtex and autocomplete-plus installed new today (23/03/2015). Unlke maxheld83's issue, I am able to have the package detect my bib file, however, autocomplete only ever suggests the first reference in the bib file and it won't autocomplete any other citations. My config file is set up as it should be.

![Image of issue](https://cloud.githubusercontent.com/assets/1608939/6783379/4e2dd3a0-d171-11e4-9c54-7d669666478a.png)

**Comment by apcshields** [comment]
Christopher,

It seems likely that the parser is blowing up somewhere early in your bib file. Can you send me the first few entries from your file, as well as anything which shows up in your Atom console?

Thanks,
Andrew

**Comment by cddesja** [comment]
Hi,
Thanks for the quick reply. Nothing shows up in the console. Could it be BibDesk's modifications that are causing the headache?  

%% This BibTeX bibliography file was created using BibDesk.
%% http://bibdesk.sourceforge.net/

%% Created for Christopher David Desjardins at 2015-03-13 08:16:37 +0000


%% Saved with string encoding Unicode (UTF-8)

@article{fahay1999essential,
  title={Essential fish habitat source document: Atlantic cod, Gadus morhua, life history and habitat characteristics},
  author={Fahay, MP and Berrien, PL and Johnson, DL and Morse, WW},
  journal={NOAA Tech. Mem. NMFS-NE},
  volume={124},
  pages={41},
  year={1999}
}

@manual{penny2015multimarkdown-u,
	Author = {Fletcher T. Penny},
	Date-Added = {2015-03-05 09:55:35 +0000},
	Date-Modified = {2015-03-05 09:56:55 +0000},
	Edition = {4.7},
	Keywords = {software, markdown},
	Title = {Multimarkdown User's Guide},
	Year = {2015},
	Bdsk-File-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YV8QHHNvZnR3YXJlL01NRF9Vc2Vyc19HdWlkZS5wZGbSFwsYGVdOUy5kYXRhTxEB3AAAAAAB3AACAAAMTWFjaW50b3NoIEhEAAAAAAAAAAAAAAAAAAAA0P+4skgrAAAABUS/E01NRF9Vc2Vyc19HdWlkZS5wZGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYek7RHdhyUERGIAAAAAAAAQADAAAJIAAAAAAAAAAAAAAAAAAAAAhzb2Z0d2FyZQAQAAgAAND/uLIAAAARAAgAANEd2HIAAAABABgABUS/AAVEuABZpdgAJNdUAAT5XQACEnoAAgBbTWFjaW50b3NoIEhEOlVzZXJzOgBjaHJpczoARHJvcGJveDoAY2hyaXNfZm9sZGVyOgBsaXRlcmF0dXJlOgBzb2Z0d2FyZToATU1EX1VzZXJzX0d1aWRlLnBkZgAADgAoABMATQBNAEQAXwBVAHMAZQByAHMAXwBHAHUAaQBkAGUALgBwAGQAZgAPABoADABNAGEAYwBpAG4AdABvAHMAaAAgAEgARAASAEhVc2Vycy9jaHJpcy9Ecm9wYm94L2NocmlzX2ZvbGRlci9saXRlcmF0dXJlL3NvZnR3YXJlL01NRF9Vc2Vyc19HdWlkZS5wZGYAEwABLwAAFQACAAz//wAAgAbSGxwdHlokY2xhc3NuYW1lWCRjbGFzc2VzXU5TTXV0YWJsZURhdGGjHR8gVk5TRGF0YVhOU09iamVjdNIbHCIjXE5TRGljdGlvbmFyeaIiIF8QD05TS2V5ZWRBcmNoaXZlctEmJ1Ryb290gAEACAARABoAIwAtADIANwBAAEYATQBVAGAAZwBqAGwAbgBxAHMAdQB3AIQAjgCtALIAugKaApwCoQKsArUCwwLHAs4C1wLcAukC7AL+AwEDBgAAAAAAAAIBAAAAAAAAACgAAAAAAAAAAAAAAAAAAAMI}}

@article{sigurjonsson:2000:seasonal,
	Author = {Sigurj{\'o}nsson, J{\'o}hann and V{\'\i}kingsson, G{\'\i}sli A},
	Journal = {Journal of Northwest Atlantic Fishery Science},
	Month = feb,
	Pages = {271--287},
	Title = {{Seasonal Abundance of and Estimated Food Consumption by Cetaceans in Icelandic and Adjacent Waters}},
	Volume = {22},
	Year = {2000}}

@article{Plaganyi:2012ff,
	Author = {Plag{\'a}nyi, {\'E}va E and Punt, Andr{\'e} E and Hillary, Richard and Morello, Elisabetta B and Th{\'e}baud, Olivier and Hutton, Trevor and Pillans, Richard D and Thorson, James T and Fulton, Elizabeth A and Smith, Anthony D M and Smith, Franz and Bayliss, Peter and Haywood, Michael and Lyne, Vincent and Rothlisberg, Peter C},
	Journal = {Fish and Fisheries},
	Month = jun,
	Number = {1},
	Pages = {1--22},
	Title = {{Multispecies fisheries management and conservation: tactical applications using models of intermediate complexity}},
	Volume = {15},
	Year = {2012}}

@techreport{anonymous:dst2,
	Address = {Reykjavik},
	Author = {{Anonymous}},
	Month = aug,
	Title = {{dst2: Development of structurally detailed statistically testable models of marine populations }},
	Year = {2004}}

@techreport{perez:1993food,
	Author = {Perez, M A and McAlister, W B},
	Number = {NMFS-AFSC-14},
	Title = {{Estimates of food consumption by marine mammals in the eastern Bering Sea}},
	Year = {1993}}

@article{ROSE:2005ix,
	Author = {ROSE, G},
	Journal = {ICES Journal of Marine Science},
	Month = oct,
	Number = {7},
	Pages = {1524--1530},
	Title = {{Capelin (Mallotus villosus) distribution and climate: a sea {\textquotedblleft}canary{\textquotedblright} for marine ecosystem change}},
	Volume = {62},
	Year = {2005}}

@article{jakobsson1999review,
	Abstract = {
The paper reviews joint international investigations of the distribution of the Atlanto-Scandian herring in relation to temperature during the period prior to the collapse of the stock in the late 1960s. The results of the international surveys clearly show that the ocean climate was relatively mild during 1950-1964. On the other hand, the years 1965-1969 were very cold and the nature of the East Icelandic Current changed dramatically. During the mild period the herring were able to cross the tongue of cold water NE and E of Iceland, while during the cold period the migration pattern of the herring as well as the feeding area shifted from north of Iceland to the Bear Island area. The mapping of the migration route of the Atlanto-Scandian herring was of great practical value for the herring industry during the 1950s and in the 1960s.},
	Author = {Jakobsson, J and {\O}stvedt, O J},
	Date-Modified = {2014-11-14 09:26:01 +0000},
	Journal = {Rit Fiskideildar},
	Keywords = {Atlanto-Scandian herring, herring, feeding migration, effect of climate change, Clupea harengus},
	Pages = {209 - 238},
	Title = {A review of joint investigations on the distribution of herring in the Norwegian and Iceland Seas 1950-1970},
	Volume = {16},
	Year = {1999},
	Bdsk-File-1 = {YnBsaXN0MDDUAQIDBAUGJCVYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKgHCBMUFRYaIVUkbnVsbNMJCgsMDxJXTlMua2V5c1pOUy5vYmplY3RzViRjbGFzc6INDoACgAOiEBGABIAFgAdccmVsYXRpdmVQYXRoWWFsaWFzRGF0YV8QGHNwZWNpZXMvaGVycmluZy8yMDA1LnBkZtIXCxgZV05TLmRhdGFPEQHCAAAAAAHCAAIAAAxNYWNpbnRvc2ggSEQAAAAAAAAAAAAAAAAAAADQ/7iySCsAAAAFRMgIMjAwNS5wZGYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhwqdCTv8wAAAAAAAAAAAABAAQAAAkgAAAAAAAAAAAAAAAAAAAAB2hlcnJpbmcAABAACAAA0P+4sgAAABEACAAA0JO/zAAAAAEAHAAFRMgABUTAAAVEuABZpdgAJNdUAAT5XQACEnoAAgBYTWFjaW50b3NoIEhEOlVzZXJzOgBjaHJpczoARHJvcGJveDoAY2hyaXNfZm9sZGVyOgBsaXRlcmF0dXJlOgBzcGVjaWVzOgBoZXJyaW5nOgAyMDA1LnBkZgAOABIACAAyADAAMAA1AC4AcABkAGYADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgAIABIAEQAEgBEVXNlcnMvY2hyaXMvRHJvcGJveC9jaHJpc19mb2xkZXIvbGl0ZXJhdHVyZS9zcGVjaWVzL2hlcnJpbmcvMjAwNS5wZGYAEwABLwAAFQACAAz//wAAgAbSGxwdHlokY2xhc3NuYW1lWCRjbGFzc2VzXU5TTXV0YWJsZURhdGGjHR8gVk5TRGF0YVhOU09iamVjdNIbHCIjXE5TRGljdGlvbmFyeaIiIF8QD05TS2V5ZWRBcmNoaXZlctEmJ1Ryb290gAEACAARABoAIwAtADIANwBAAEYATQBVAGAAZwBqAGwAbgBxAHMAdQB3AIQAjgCpAK4AtgJ8An4CgwKOApcCpQKpArACuQK+AssCzgLgAuMC6AAAAAAAAAIBAAAAAAAAACgAAAAAAAAAAAAAAAAAAALq}}

@article{Thorarinsdottir:1996quahogdist,
	Author = {Th{\'o}rarinsd{\'o}ttir, Gudr{\'u}n G and Einarsson, S{\'o}lmundur T},
	Journal = {Journal of the Marine Biological Association of the United Kingdom},
	Month = nov,
	Pages = {1107--1114},
	Title = {{Distribution, abundance, population structure and meat yield of the ocean quahog, <i>Arctica islandica</i>, in icelandic waters}},
	Volume = {76},
	Year = {1996}}

**Comment by cddesja** [comment]
OK, I can confirm that this bug has to do with something in BibDesk. If I copy a couple of articles from Google Scholar into a text document, save it as literature.bib, and try to use your package on this new file, it will work as intended. However, if I open the literature.bib file in BibDesk, save it, and then try to use your package, it no longer works. Any ideas why?

**Comment by apcshields** [comment]
Christopher,

Ah! Thanks for testing that! I’ll have to review my notes on the BibTeX format and my parser again. Hopefully I’ll have an answer and a patch in a few days.

I’ll keep you updated.

Andrew

**Comment by cddesja** [comment]
Thanks. If you need anything else let me know. FYI, this is [BibDesk](http://bibdesk.sourceforge.net/)

**Comment by apcshields** [comment]
Christopher,

Turns out that the BibTeX parser needed to normalize the BibTeX key names to lowercase—BibDesk appears to be inconsistent about this. v0.5.6 should take care of this.

Thanks!
Andrew

**Comment by maxheld83** [comment]
works now for me, too! Great. thanks @apcshields

**Comment by koppanm** [comment]
I understand this was already a long time ago, but I am unable to get bibtex autocomplete work on my mac. I followed ALL available instructions, reinstalled everything, the only thing I find is that the source .bib file is not available (although specified correctly). In developer console that's what I see: 
"Failed to load resource: net::ERR_FILE_NOT_FOUND" 
and 
"Uncaught (in promise) Error: Total of weights cannot exceed 1
    at e.value (/Users/MacSzallott/.atom/packages/autocomplete-bibtex/node_modules/fuse.js/dist/fuse.js:9)
    at new e (/Users/MacSzallott/.atom/packages/autocomplete-bibtex/node_modules/fuse.js/dist/fuse.js:9)
    at ReferenceProvider.<anonymous> (/Users/MacSzallott/.atom/packages/autocomplete-bibtex/lib/provider.js:138)
    at Generator.next (<anonymous>)
    at step (/Users/MacSzallott/.atom/packages/autocomplete-bibtex/lib/provider.js:1)"
Very much frustrating. Could someone please help?
