### ISSUE TITLE
Weird UI behavior (part 2)

### ISSUE THREAD

**Issue by tpoisot** [apcshields/autocomplete-bibtex#19]
Generally, the pop-up is not extremely informative, because it appears around the cursor, which is (I find) often problematic when working on text:

![capture d ecran de 2015-04-09 14 50 45](https://cloud.githubusercontent.com/assets/579329/7074367/d733b576-dec7-11e4-998b-a9547f907208.png)

And a lot of space is lost to nothing, with the title compressed. I wondered if the two following adjustments would not be better
1. The pop-up appears at the top of the screen, as in [https://github.com/mangecoeur/Citer] 
2. There are three "columns", with key, authors, then shortened title. If the three were somehow aligned, the pop-up would gain a lot in readability.

Finally, I was not able to find the following in the docs: how are the suggested completions sorted?

**Comment by maxheld83** [comment]
I have the same problem; the UI just doesn't look as nice as, in the screenshot in the readme ...
