### ISSUE TITLE
Suggestion - allow citation search through UI

### ISSUE THREAD

**Issue by mangecoeur** [apcshields/autocomplete-bibtex#24]
It would be handy if as well as autocompleting citekeys, you could search through them directly through some kind of UI - such as the command panel. I implemented something similar for Sublime Text - https://github.com/mangecoeur/Citer - but am migrating to Atom

**Comment by apcshields** [comment]
mangecoeur,

That sounds interesting and useful, but I don’t at the moment have time to put it together. If you or a friend would like to work on it, though, that’d be great!

Andrew

**Comment by apcshields** [comment]
@mangecoeur,

Do you want to set up any default key mappings for this?

Andrew

**Comment by mangecoeur** [comment]
I usually prefer to let people choose their own shortcuts, but if you have
a policy of giving everything a shortcut I don't mind adding some

**Comment by apcshields** [comment]
That's fine.
