### ISSUE TITLE
Insertion box disappears when typing a colon

### ISSUE THREAD

**Issue by adunning** [apcshields/autocomplete-bibtex#28]
Zotxt generates citekeys in the format of `@bloggs:2015title`. The autocomplete box disappears, however, when one types a colon.

**Comment by apcshields** [comment]
adunning,

Oops. That should be an easy fix, and I'll try to get it done this weekend.

Sorry!
Andrew

**Comment by adunning** [comment]
Not a problem; thank you for all your work on this!

**Comment by apcshields** [comment]
Ok—not as easy a fix as I had thought. Still working on it, though!

**Comment by mangecoeur** [comment]
This appears to be working in the latest release
