### ISSUE TITLE
Slow package activation

### ISSUE THREAD

**Issue by mangecoeur** [apcshields/autocomplete-bibtex#29]
From TimeCop, package activation takes over 1500ms on my system with a bibfile containing 307 entries (500KB) (for comparison, the next slowest item on activation takes 76ms). I suspect this is due to reading the bibfile on load. 

I would suggest implementing `serialize` for the package to dump the current bibfile data in an efficient way (e.g json or binary blob) and checking on load if the bibfile has changed since last opening, and loading the data accordingly.

**Comment by apcshields** [comment]
mangecoeur,

That sounds like a good plan, and something I'd like to pursue—but I don't know how much time I'll have to do it in the near future. If you (or anyone else) feels like doing it, feel free to submit a pull request!

Thanks,
Andrew

**Comment by mangecoeur** [comment]
So i added serialization support (needed some tweaks to the classes), packages now "warm" loads in 204ms instead of 1500ms! (still not sure why it takes even 200+ms but It's still a big improvement)

**Comment by mangecoeur** [comment]
p.s. most time apparently spent in "sugar", I disabled that in my latest commit and brought load time down to 130ms

**Comment by mangecoeur** [comment]
pps realised what sugar was supposed to do (add string function for titlecaps and string truncate) but I think it takes unreasonably long to load just for that, so added a titlecaps function (based on code by John Gruber of markdown fame no less) and some logic to do the title truncation.

**Comment by apcshields** [comment]
Yeah, I need to remove the ‘sugar’ dependency—it appears to be breaking the package entirely for a handful of users—but I haven’t had the patience to go through and weed it out.

Andrew

**Comment by adunning** [comment]
Thanks for looking at this, @mangecoeur; the present version takes 5666ms to load with my library.

Might it further improve performance to parse JSON rather than BibTeX? I'm using the autocomplete plugin for use with Pandoc, taking citations from Zotero using the Better BibTeX plugin to export both a BibTeX library (for the autocompletion plugin) and Pandoc JSON (new in version 1.1 of the plugin: this is simply CSL JSON with the citation key used as an ID, and postprocessing for the notes field). I find that Pandoc can read this more reliably than BibTeX.

**Comment by mangecoeur** [comment]
@adunning adding support for Pandoc JSON is probably a separate issue, good idea though ...

**Comment by apcshields** [comment]
Yes.

Andrew, can you file a separate issue with this?

Thanks,
Andrew

**Comment by adunning** [comment]
Sorry about that – see #31.

**Comment by apcshields** [comment]
No problem. Thanks!

**Comment by mangecoeur** [comment]
@apcshields let me know if you want me to fix up anything else in order for you to merge the PR

**Comment by apcshields** [comment]
Thanks, mangecoeur. I just haven’t had time to look at it yet. It’s on my agenda for after work today.

Andrew

**Comment by apcshields** [comment]
Closed by 890687e.

**Comment by adunning** [comment]
Brilliant – down to 61ms here.
