### ISSUE TITLE
Support for Pandoc/CSL JSON

### ISSUE THREAD

**Issue by adunning** [apcshields/autocomplete-bibtex#31]
The native format of Pandoc-citeproc is CSL JSON, which is also what Zotero uses, but there was not formerly a way to export this directly, which led to many people using BibTeX instead. As of version 1.1, the Better BibTeX plugin has a 'Pandoc JSON' option that will export CSL JSON, using its generated citation key as an ID, and applying postprocessing to the notes field (allowing one to use CSL variables not yet provided in Zotero's interface). Given that it's now possible to use this format directly, it would be ideal if the autocomplete plugin could parse this as well as BibTeX.

From the user's perspective, the simplest way to implement this would likely be to detect the file extension of the bibliography provided (i.e. `.bib` vs. `.json`). Or would it be more efficient to fork this plugin and have a separate package altogether?

**Comment by retorquere** [comment]
BTW not only can this format now be exported directly from Zotero, it will keep that file updated too if you want.

**Comment by tpoisot** [comment]
I second. Support for citeproc json or citeproc yaml (which are used by pandoc-citeproc) would be a huge plus. Bibtex is oftentimes an outdated format, and citeproc json/yaml solves many problems.

**Comment by apcshields** [comment]
I'm in favor of this, too... it's just a matter of having time to do anything about it. As always, anyone who wants to contribute is welcome.




Andrew



—

**Comment by tpoisot** [comment]
Point well taken, @apcshields -- where in the code should I start to look to see if my limited coffeescript skills are enough to make it happen?

**Comment by apcshields** [comment]
In `lib/provider.coffee`, the `buildWordListFromFiles` function calls the `readBibtexFiles` function. We'd probably want a function parallel to the latter which could be called from the former when appropriate. 




Andrew



—

**Comment by tpoisot** [comment]
OK, so the internal representation of the bibtex objects gave me some pain, but I think I'm almost there for YAML files. I will submit a PR soon.

**Comment by apcshields** [comment]
Hmmm. Any particular thing about how the bibtex objects are structured?

**Comment by tpoisot** [comment]
It's just the `.entryTags` things, which are a bit confusing. I'm making progress.

**Comment by tpoisot** [comment]
OK, let's maybe move the discussion of this point to #38 ?

**Comment by tpoisot** [comment]
As of now, my fork (https://github.com/tpoisot/autocomplete-bibtex/) works for `yaml`, `json` and `bibtex`.

@apcshields  -- are you interested in merging?

**Comment by tpoisot** [comment]
(I have also update the code to use autocomplete-plus v2, which solves #18 and #19

**Comment by adunning** [comment]
This is fantastic; thanks for your work on it!

Is this going to be merged into the original, or remain a separate fork?

**Comment by apcshields** [comment]
Andrew,




I'd like to look over it first, but had no time this weekend. If somebody else wants to double check it, that would be great.




(Not that I think there's anything wrong with Timothée's work, but a second pair of eyes can catch a lot of things the first pair didn't.)




@tpoisot I'm assuming (based on your message last week) that you consider this ready to merge. Can you submit a pull request?




Thanks,

Andrew



—

**Comment by lodestone** [comment]
:+1: on a PR/merge of @tpoisot's work on his fork. I dug around in there to fix a bug with the template format and he even fixed one of my bugs! Hurray for open source!

**Comment by apcshields** [comment]
Thanks, @lodestone!

@tpoisot I'm traveling this weekend, so, since I'm not sure when I'll have a chance to work with you on this, I've made you a collaborator on this repository. Feel free to merge your changes when you're ready.

:)

**Comment by tpoisot** [comment]
Sorry for the delay -- I'm not 100% ready to merge yet. There are still some weird UI things that happen for reasons I'm not sure of, and I'd like to add some support to the bibtex parser too (maybe).

**Comment by adunning** [comment]
Am I correct in thinking that this is now included in the development version? (Can't test it, as I can't get it to install.) If so, let me know if you need help with getting a new release out, since this would be great to have.

**Comment by apcshields** [comment]
Andrew,




I'm still fixing bugs that I'm encountering after the last two big merges (of which this one). As soon as they're fixed (some time in the next week?), we'll release a new version which includes this.




Andrew



—

**Comment by adunning** [comment]
No particular rush. Thank you!
