### ISSUE TITLE
OSX10.10.4 - Atom 1.0.3 - Autocomplete-bibtex 0.6.0

### ISSUE THREAD

**Issue by jpoa** [apcshields/autocomplete-bibtex#34]
Greetings!

Somehow I cannot get the autocomplete to work :/

I have tried with more than one bib file, I have tried to use md files, non md files, I have restarted atom several times, I have checked for messages on the developer tools, I started Atom from the CLI and still no clue.

Maybe its something I am doing wrong but right now I am at a loss, any pointers on what I can do?

It simply just does not react after I type the @

Best regards!

**Comment by apcshields** [comment]
jpoa,

Do you feel comfortable posting your config file and any contents of the error console?

Thanks,
Andrew

**Comment by jpoa** [comment]
Hey @apcshields thank you for the feedback.

I was hoping that we could sort this bug out but I was doing an install to a friend who needed to be up and running quickly with markdown + bibtex for citations, in the end I resorted to Sublime3+Citer which worked.

As I don't have access to the running setup now I am closing this issue as I cannot debug it.
