### ISSUE TITLE
Extra { } brakets shown for Mendeley bibtex titles

### ISSUE THREAD

**Issue by mangecoeur** [apcshields/autocomplete-bibtex#41]
It seems Mendeley's bibtex export wraps titles in double curly brakets : `{{ ... }}`. Not sure if this is normal bibtex, but in any case only the outer pair stripped out by the bibtex parser so all titles appear as `{title}`. Not sure if this is a bug in mendeley or in the parser though, not sure what the  bibtex standard is...

**Comment by mangecoeur** [comment]
note - looks like it is "valid" bibtex (as valid as bibtex can be, given it's pretty ill-defined) - the python bibtexparser library seems to process it ok https://github.com/sciunto-org/python-bibtexparser/

**Comment by apcshields** [comment]
Yes, I agree that the double-brackets are valid and should be preserved.



—
