### ISSUE TITLE
Usage with files other than .md

### ISSUE THREAD

**Issue by franvillamil** [apcshields/autocomplete-bibtex#45]
Is there any way to use the package with files different than .md? In particular, I'd like it to activate itself with .tex files as well. By the way, great job! Thanks a lot!

**Comment by apcshields** [comment]
Francisco,




Yes, you can edit the 'scope' configuration setting to match the scope you'd like autocomplete-bibtex to be triggered in. I don't know the appropriate scope for tex files off the top of my head, and I'm traveling without my computer at the moment, so I can't figure it out, but you should be able to find it using the information in [this documentation](https://atom.io/docs/latest/behind-atom-scoped-settings-scopes-and-scope-descriptors). I would expect it to be something like `.source.tex`.




When I'm back home again, if you're still having trouble, I'll be happy to help you out!




Thanks!

Andrew



—

**Comment by franvillamil** [comment]
Thanks Andrew! It is solved, the scope was ".text.tex.latex", so my settings now are

    scope: ".source.gfm, .text.tex.latex"

**Comment by apcshields** [comment]
Great!




Strange that Markdown is considered 'source', but LaTeX is considered 'text'....



—

**Comment by tpoisot** [comment]
I also added `.text.md` to add support to the `language-markdown` package.

**Comment by mangecoeur** [comment]
closed by latest release
