### ISSUE TITLE
 Autocomplete bibtex in latex files does not work? 

### ISSUE THREAD

**Issue by BennX** [apcshields/autocomplete-bibtex#47]
I am more or less new to Atom but feeling quit good till now. I am trying to setup Atom for writing latex so i installed the packages i need for it.

    autocomplete-bibtex
    language-latex
    latex
    pdf-view

Everything seem to work great and i even wrote my own snippets. But the bibtex is not working properly and i dont know whats wrong.

I set p autocom. -bibtex like this:
```
  tabs: {}
  minimap: {}
  "keyboard-localization": {}
  "atom-ctags":
    autoBuildTagsWhenActive: true

  "autocomplete-plus":{}

  "autocomplete-bibtex":
    bibtex: [
      "D:\\Git_repo\\masterarbeit\\Masterarbeit Latex\\bib\\literatur.bib"
    ]
    resultTemplate: "\\cite[S. $1]([KEY])"
    scope: ".text.tex.latex"

  "autocomplete-clang": {}
  latex: {}
```
But it does not give me any suggestions on my bib which for example contains:
```
@book{fundamentals,
 author = {Elmasri, Ramez and Navathe, Sham},
 year = {2007},
 title = {Fundamentals of database systems},
 address = {Boston},
 edition = {5th ed.},
 publisher = {{Pearson Addison Wesley}},
 isbn = {032141506X}
}
```
but it doesnt complete me on `@fundamental` ... or `@Elmasri` or anything else.

I did try to change the scope to text.tex.latex and also to .text.latex and so on.
And i also saw and tried the solution of #45 
- changed the path to use / instead of \\ 
- Changed the folder to C:\bib\literatur.bib 

Nothing result in any completation.

Moreover is it possible to extend the \cite template to something like this:` \cite[S. $1] ([KEY])` and is it possible to cite by the bib key because some of the titels i am using do not have a clear Author (Like ACM 2002 does not an author? 

So what have i dont wrong? 
Is it the whitespace inside of the path? (well i tried a path without and it didnt change anything)

I am  on Windows 10 x64:
Installed community packages:
* autocomplete-clang
* autocomplete-bibtex
* atom-ctags
* keyboard-localization
* language-latex
* latex
* pdf-view

**Comment by maecky** [comment]
I have the exact same problem, can't get it to work on Win10 64 bit. @BennX  have you found a solution?

**Comment by BennX** [comment]
@maecky I am sorry to tell you that, but i haven't found andy solution yet and i gave up on this.

**Comment by apcshields** [comment]
@BennX @maecky,

I don't have a Windows 10 machine I can test on, but if you open up the
Developer Tools in Atom (should be something like View > Developer > Toggle
Developer Tools), go to the Console, and send any errors that are there, I
might be able to figure out what's happening.

Thanks,
Andrew

**Comment by maecky** [comment]
@BennX  @apcshields  I debuged it already myself and found 2 bugs. At the moment I am testing if everything is working...
I will make a pull request.
