### ISSUE TITLE
Cannot update or change .bib file

### ISSUE THREAD

**Issue by breschke** [apcshields/autocomplete-bibtex#48]
I am using Atom 1.2.3 and autocomplete-bibtex 6.1. I am trying to update my .bib file, but new entries are not reflected in the autocomplete when I type. I have tried restarting Atom, no luck. I have even disabled/uninstalled autocomplete-bibtex 6.1 and still new entries are not reflected. Now, I find that I cannot even change the .bib file to something else: the entries in my original .bib file are the ones reflected in the autocomplete, even though I have changed the setting to a new .bib file.

I suspect this is some error with updating/deleting a temp file database? Where is the default location for this database?

**Comment by breschke** [comment]
A suggestion in #37 helped me. For those using Linux or OS X, close Atom, then use the 'touch' command at the terminal:

`touch /path/to/references.bib`

Then restart Atom. This fixed the problem. It is cumbersome to have to do this every time I modify the .bib file, however.

**Comment by tpoisot** [comment]
I never once had to do this on Linux. This is weird.



Sent from a mobile device. Pardon the typos/brevity.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On ven., nov. 20, 2015 at 5:20 PM, Brian Reschke < notifications@github.com [notifications@github.com] > wrote:
A suggestion in #37 [https://github.com/apcshields/autocomplete-bibtex/issues/37] helped me. For those using Linux or OS X, close Atom, then use the 'touch'
command at the terminal:

touch /path/to/references.bib

Then restart Atom. This fixed the problem. It is cumbersome to have to do this
every time I modify the .bib file, however.

—
Reply to this email directly or view it on GitHub
[https://github.com/apcshields/autocomplete-bibtex/issues/48#issuecomment-158542327] .[https://github.com/notifications/beacon/AAjXAciNB8KtHfvx_QCTI5B_CuNoHYdoks5pH5QrgaJpZM4Gmubx.gif]
