### ISSUE TITLE
Citation entries parsed from JSON are in a different format than ReferenceProvider.buildWordList expects

### ISSUE THREAD

**Issue by apcshields** [apcshields/autocomplete-bibtex#49]
`ReferenceProvider.buildWordList` expects the citation entries in `@bibtex` to have either `citation.entryTags.author` or `citation.entryTags.editor`. `citeproc.parse` currently returns author information only in `citation.entryTags.authors`, which means that the citation is ignored by `buildWordList`.

**Comment by tpoisot** [comment]
There is a function to parse citeproc to the format used internally, this should
be an easy fix. No time to look at it right now (but I though I had tested with
books, sorry for the oversight)



Sent from a mobile device. Pardon the typos/brevity.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.67&pv=5.1.1&source=email_footer_2] On ven., nov. 20, 2015 at 6:19 PM, apcshields < notifications@github.com [notifications@github.com] > wrote:
ReferenceProvider.buildWordList expects the citation entries in @bibtex to have either citation.entryTags.author or citation.entryTags.editor . citeproc.parse currently returns author information only in citation.entryTags.authors , which means that the citation is ignored by buildWordList .

**Comment by apcshields** [comment]
Timothée,

Yep, I've just got to stop for the evening and want to document what I'm running into.

Thanks!
Andrew

**Comment by apcshields** [comment]
Closed by 24cc381f82dcc67027bc589a5da1624630da2fc7.
