### ISSUE TITLE
Can't install in Atom

### ISSUE THREAD

**Issue by jcpsantiago** [apcshields/autocomplete-bibtex#52]
I have git installed and other packages install without a hiccup. Windows 7 Can I install it manually?

```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/apcshields/zotero-bibtex-parse.git#v1.2.0 resetting remote C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Joao Santiago\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/zotero-bibtex-parse.git C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a: Cloning into bare repository 'C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a'...
npm ERR! git clone --template=C:\Users\Joao Santiago\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/zotero-bibtex-parse.git C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\Joao Santiago\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/zotero-bibtex-parse.git C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a: github.com[0: 192.30.252.130]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Joao Santiago\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Joao Santiago\\AppData\\Local\\atom\\app-1.2.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Joao Santiago\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Joao Santiago\\.atom\\.apmrc" "install" "C:\\Users\\JOAOSA~1\\AppData\\Local\\Temp\\d-115111-2840-1f3hymq\\package.tgz" "--target=0.34.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Joao Santiago\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by apcshields** [comment]
@elgitmariachi,

I've never installed the package manually on Windows, but you should be able to do it by cloning the package, installing the package dependencies, and then using `amp link [<package_path>]`. (See the [Atom packages command line documentation](https://atom.io/docs/latest/using-atom-atom-packages#command-line) and the output of `apm help link`.)

Let me know how it goes!

Andrew

**Comment by avonmoll** [comment]
Note that I've gotten a very similar error when trying to update the `script` package for Atom, but have been able to update/install other packages just fine.

I had this same issue and attempted a manual install as recommended. Cloned the repo and attempted `apm install` in the repo's directory. I got an error dialogue similar to the original one. Is there a manual step I needed to carry out in order to install dependencies before attempting the install command?

For reference:
```
PS C:\Users\VonmolAL\Documents\Atom\package-source\autocomplete-bibtex> apm install
Installing modules failed
npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/apcshields/zotero-bibtex-parse.git#v1.2.0 resetting remote C:\Users\VonmolAL\.at
om\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0b26a because of error: { [Error: Command fail
ed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\VonmolAL\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/
zotero-bibtex-parse.git C:\Users\VonmolAL\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0
b26a: Cloning into bare repository 'C:\Users\VonmolAL\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-pa
rse-git-a6e0b26a'...
npm ERR! git clone --template=C:\Users\VonmolAL\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/
zotero-bibtex-parse.git C:\Users\VonmolAL\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0
b26a: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\VonmolAL\.atom\.apm\_git-remotes\_templates --mirror git://github.com/apcshields/
zotero-bibtex-parse.git C:\Users\VonmolAL\.atom\.apm\_git-remotes\git-github-com-apcshields-zotero-bibtex-parse-git-a6e0
b26a: github.com[0: 192.30.252.128]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\VonmolAL\\Documents\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\VonmolAL\\Documents
\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\VonmolAL\\.atom\\.apm\\.ap
mrc" "--userconfig" "C:\\Users\\VonmolAL\\.atom\\.apmrc" "install" "--target=0.34.5" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\VonmolAL\.atom\.apm\_git-remotes\git-github-com-apcshiel
ds-zotero-bibtex-parse-git-a6e0b26a'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by apcshields** [comment]
@jcpsantiago, @avonmoll,

Are you trying to perform the install while connected to a network that uses a proxy, a la atom/atom#2268?

Thanks,
Andrew

**Comment by avonmoll** [comment]
I was finally able to install autocomplete-bibtex by doing the following:

1. clone autocomplete-bibtex
1. `cd autocomplete-bibtex`
1. `mkdir node_modules`
1. `cd node_modules`
1. download the ZIP of zotero-bibtex-parse-v1.2.0, unzip
1. `cd zotero-bibtex-parse`
2. change zotero-bibtex-parse `package.json` from version 1.0.0 to 1.2.0
2. `npm install`
3. `cd ../..`
3. change the zotero-bibtex-parse dependency in autocomplete-bibtex `package.json` to `>=1.2.0`
3. `apm install`

I think the original problem is twofold: 
1. the zotero-bibtex-parse repository has a v1.2.0 tag, but no corresponding release; also, the latest commit with v.1.2.0 tag still shows v.1.0.0 in `package.json`
2. autocomplete-bibtex dependency for zotero-bibtex-parse points to `git://github.com/apcshields/zotero-bibtex-parse.git#v1.2.0`, which can't be reached for some reason (i.e. git clone on that URL always fails for me)

**Comment by apcshields** [comment]
@avonmoll 

I've fixed the first problem. Sorry about that.

As for the second, I don't think `git clone` is supposed to understand that style of URL. I think the better test is `npm install git://github.com/apcshields/zotero-bibtex-parse.git#v1.2.0`, which works for me. Does it work for you?

Thanks,
Andrew

**Comment by avonmoll** [comment]
When I try that command I get an error similar to OP and the one I posted earlier in this thread. I'm not sure what the root cause is, but it almost seems as if npm is trying to access the repo with a URL that doesn't exist. It could be proxy-related, but I typically don't have any issues installing other packages with npm and apm.

**Comment by avonmoll** [comment]
Just curious:

Why not merge [zotero-bibtex-parse (resilient)](https://github.com/apcshields/zotero-bibtex-parse/tree/resilient) into [zotero-bibtex-parse (master)](https://github.com/apcshields/zotero-bibtex-parse/tree/master) and change [autocomplete-bibtex/package.json](https://github.com/apcshields/autocomplete-bibtex/blob/master/package.json#L25) to `"zotero-bibtex-parse": ">=1.2.0"`?

**Comment by vitasiku** [comment]
@avonmoll your detailed step-by-step guide helped me to setup as I experienced the same problem reported here.

**Comment by mangecoeur** [comment]
For simplicity I plan to vendorise the bibtex-pare package to remove the dependency on git (since that can be a pain especially on windows).

**Comment by apcshields** [comment]
Good!
