### ISSUE TITLE
Restart need after changing bibtex

### ISSUE THREAD

**Issue by ihrke** [apcshields/autocomplete-bibtex#56]
When adding/changing the bibtex-files in `config.cson` (`bibtex`-field), the changes are not immediately reflected but Atom must be restarted. In the console, we get

```
TypeError: path must be a string(…) provider.coffee:150
```

Checking that line, I find that upon saving `config.cson`, the variable `bibtexFiles` does not hold an array as expected but an `Object` that contains two arrays, one called `oldValue` one called `newValue`. This is the reason for the strange error. I think `provider.coffee` should handle this case by just extracting `newValue` from this object in this case.

**Comment by mangecoeur** [comment]
closing in favour of #57
