### ISSUE TITLE
Feature request: Enable .bib files to be automatically reloaded on change

### ISSUE THREAD

**Issue by anthillsocial** [apcshields/autocomplete-bibtex#57]
Are there any plans for a trigger to enable .bib files to be reloaded without restarting atom?
This would be a VERY useful feature.
BTW Thanks for the great work.

**Comment by apcshields** [comment]
Tom,




Definitely. But I don't know how soon—that's the most fragile and finicky part of the package.




Thanks!

Andrew



—

**Comment by chriskrycho** [comment]
I *think* I have a pretty good idea how to make this work (using [`fs.watchFile`](https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener)), but I'll need to spend some time playing with it to be sure. If I get it there, I'll make a PR for it.

**Comment by apcshields** [comment]
Chris,
Sounds great!
Andrew

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.6.23&pv=9.2.1&source=email_footer_2]
On Sat, Feb 27, 2016 at 4:59 PM, Chris Krycho <notifications@github.com> wrote:
I think I have a pretty good idea how to make this work (using fs.watchFile
[https://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener] ), but I'll need to spend some time playing with it to be sure. If I get it
there, I'll make a PR for it.

—
Reply to this email directly or view it on GitHub
[https://github.com/apcshields/autocomplete-bibtex/issues/57#issuecomment-189735786] .[https://github.com/notifications/beacon/ABIE8ptOEoB4TLl2FpC7gQp6os0RR_9bks5pohO-gaJpZM4G_phQ.gif]

**Comment by mangecoeur** [comment]
@anthillsocial FYI - although less convenient, there is a command to force-reload the bibliography included, so at least you don't have to restart Atom

**Comment by Playnary** [comment]
@mangecoeur That's great, but what ist that command? :) If it exists it should definitely be mentioned in the readme. I couldn't find anything in the keybindings either.

**Comment by NoxMortem** [comment]
ctrl+p Bibliography:Update However, it does not work. I have Zotero running with keep updated and can see that this entry is added to my bib file:

    @techreport{blub2123,
    timestamp = {2017-11-05T16:13:40Z},
    title = {Blub 2123}
    }

but autocomplete-bibtex is clearly failing to find this entry.

**Comment by mangecoeur** [comment]
@NoxMortem hopefully the latest change should address this, could you test the development version?

**Comment by NoxMortem** [comment]
I tested 0.7.1 and it seems to work. A filewatcher with automatic bibliography reload on file changes would be amazing, but this at least avoids having to restart atom every time I change or add a key in Zotero.

**Comment by mangecoeur** [comment]
in theory there is also a file watcher registered, needs to be tested in the wild i guess.

**Comment by NoxMortem** [comment]
@mangecoeur definetly works now in v.1.0. I just tested it and I am super happy that my zotero+better bibtex+atom-autocomplete-bibtex chain now works and saves me many clicks :)
