### ISSUE TITLE
Feature request: export all cited items of the current file

### ISSUE THREAD

**Issue by daijiang** [apcshields/autocomplete-bibtex#58]
I know it may be beyond the scope of this great package, but is it possible to let users to export all cited items into another file? For example, we may put all of our references in a big bib file but for one paper we only cited a small subset of them. When we submit the paper, it will be nice to just submit a bib file with the items that we cited (not the big bib file).

Does this make sense? Is this feature already exist (from this or other Atom packages)?

Thank you again for the great work.

**Comment by apcshields** [comment]
@daijiang,

I think this is outside the scope of autocomplete-bibtex, but it sounds like an excellent idea. To my knowledge, there isn't an existing package that does this. If you find (or make) one, I'd love to use it!

Thanks,
Andrew
