### ISSUE TITLE
New release / name change

### ISSUE THREAD

**Issue by tpoisot** [apcshields/autocomplete-bibtex#59]
Hi,

So it seems that 0.6.2 is still bibtex only. Is it time to do a new release, or a name change?

**Comment by apcshields** [comment]
Timothée,
If we're confident what we've got is ready, both.
I just have had even less time lately.
Andrew

On Fri, Apr 22, 2016 at 2:48 PM, Timothée Poisot <notifications@github.com> wrote:
Hi,

So it seems that 0.6.2 is still bibtex only. Is it time to do a new release, or a name change?

**Comment by apcshields** [comment]
Can you confirm that the most recent commit is working as you would expect?

**Comment by tpoisot** [comment]
Actually, no. There is a fair amount of broken things, and some work in progress (like the search panel).

I've updated my fork with the citeproc-only things https://github.com/tpoisot/autocomplete-citeproc -- this version is working, but of course bibtex is no longer supported

**Comment by mangecoeur** [comment]
The citeproc/CSL is now in the latest release and should be working, along side the search panel and other goodies...
