### ISSUE TITLE
Migrate Back To autocomplete-plus

### ISSUE THREAD

**Issue by joefitzgerald** [apcshields/autocomplete-bibtex#6]
We're making major changes to autocomplete-plus, and the Atom 1.0 API changes will increasingly cause issues for your fork. 

Could you document the changes you've made to your autocomplete-plus-minimal fork so that we can integrate them into the main package?

Also, please don't directly depend on autocomplete-plus; get at `Provider` and `Suggestion` via the package API: https://github.com/atom-community/autocomplete-plus/wiki/Tutorial:-Registering-and-creating-a-suggestion-provider

**Comment by joefitzgerald** [comment]
FYI, https://github.com/atom-community/autocomplete-plus/releases/tag/v2.0.8 - I removed `.md` files from the default file blacklist.

**Comment by apcshields** [comment]
Thanks!


I'll update the docs.


—
