### ISSUE TITLE
No autocomplete popup since Atom 1.8

### ISSUE THREAD

**Issue by nylki** [apcshields/autocomplete-bibtex#60]
Hi,
After the update to Atom 1.8 without changes of configuration I don't get the autocomplete popup when typing `@` anymore.
Any idea what could be the cause? Can I possibly help to debug?

**Comment by nylki** [comment]
Removed the entry in *config.cson* and uninstalled and reinstalled `autocomplete-bibtex` via `apm` and it does work again.

**Comment by apcshields** [comment]
Thanks, Tom!
