### ISSUE TITLE
Integration with language-markdown

### ISSUE THREAD

**Issue by humanfactors** [apcshields/autocomplete-bibtex#61]
This package has poor integration with the [language-markdown](https://github.com/burodepeper/language-markdown) package which is a good standard, particularly for those doing more than GFM markdown. Could this autocomplete-bibtex be extended to language-markdown?

**Comment by nylki** [comment]
@humanfactors I experienced as well that `autocomplete-bibtex` doesn't work with `language-markdown`. The support is already implemented however, but unfortunately not yet published. See the relevant line: https://github.com/apcshields/autocomplete-bibtex/blob/06a6be9de1fec78e1f582454954a8599857e71ac/lib/main.coffee#L16

The version you install in Atom (via apm or the GUI) does not have `.text.md` (which `language-markdown` uses) in the default scope defined.
As soon as @apcshields publishes a new release, the support should be in.

In the meantime, you can edit the line yourself, in your local copy of the package, to look like the line linked above (to include `.text.md`). That worked for me.
You could also just clone the repo to your `packages/` directory to have the new version.

**Comment by humanfactors** [comment]
Cheers for that update, that was the solution I used on my local copy to get it working (should have posted), but it is good to have a formal record of this process. Cheers

**Comment by mangecoeur** [comment]
This should be fixed in the latest release
