### ISSUE TITLE
Using \cite{} in a tex file included via input{} does not reference main .bib file

### ISSUE THREAD

**Issue by cjm715** [apcshields/autocomplete-bibtex#63]
I have a main script that looks like this:

```
\documentclass[pre,aps,nofootinbib,11pt,notitlepage]{revtex4-1}
\usepackage{epsfig,graphics,amssymb,amsmath,subeqnarray,
setspace,graphicx,amsthm,subfigure, mathrsfs}
\usepackage{color,bm}
\usepackage{multirow}
%\usepackage{hyperref}

\def\e{\epsilon}
\def\b{\bm}
\begin{document}

    \title{Title}
    \author{author}
    \date{\today}
    \begin{abstract}
        \input{abstract}
    \end{abstract}

    \maketitle

    \section{Introduction}
        \input{sections/introduction}

    \section{Mathematical model}
        \input{sections/mathematical_model} %Done

    \bibliographystyle{unsrt}
    \bibliography{ADPaper}

\end{document}
```

The tex file, sections/introduction.tex, looks like : 
`
some text... \cite{}
`
The problem is that the \cite{} command does not provide autocomplete suggestions. How do I get \cite{} to 'talk' with the ADPaper.bib file in the main folder?

**Comment by apcshields** [comment]
Chris,

I'm sorry; if I understand the question, I don't think the parser autocomplete-bibtex uses is sophisticated enough to handle that case. You should add the included file to the list of files that the parser searches for works it can suggest.

Also, although you can set ac-bt up to output '\cite{[key]}', you will still trigger it with the '@' key.

Andrew

**Comment by gncs** [comment]
To avoid confusing bibtex files from different papers / projects, I use another add-on called [Project Manager](https://github.com/danielbrodin/atom-project-manager). I creates a file `projects.cson` (in the same directory where you keep your `config.cson`) which allows you to apply project wide settings.
For the project `latex-test` I have something like:
```
...
{
    title: "latex-test"
    paths: [
      "/home/gncs/documents/latex"
    ]
    settings:
      "autocomplete-bibtex":
        bibtex: [
          "/home/gncs/documents/latex/references.bib"
        ]
        resultTemplate: "\\cite{[key]}"
        scope: ".text.tex.latex"
  }
...
```
**Note**: I added the "autocomplete-bibtex" part - the rest was done by the addon.

**Comment by mangecoeur** [comment]
closing as solved by project-manager
