### ISSUE TITLE
autocomplete not working-but no obvious error

### ISSUE THREAD

**Issue by jamgreen** [apcshields/autocomplete-bibtex#64]
I recently installed the package in latest version of atom, followed the readme instructions on modifying the .cson settings, though i did set the file blacklist in the autocomplete-plus settings and not .cson settings.

The packages are installed and updated and I still do not get the autocomplete window when starting to type a citation. I looked at issue #13 and checked the dev console but I'm not seeing any errors (see attached screenshot). Admittedly this is my first foray into using a tool like this so I may be missing something quite basic, but having checked the other issues I am still at a loss. I'm running windows 10 version 1607.

<img width="586" alt="devcapture" src="https://cloud.githubusercontent.com/assets/7783415/19360974/a17f907c-9135-11e6-8878-95a6170cd5e3.PNG">

**Comment by mangecoeur** [comment]
You might have to change the default autocomplete settings - in some cases they are set to only show when you hit tab.
