### ISSUE TITLE
New release from master?

### ISSUE THREAD

**Issue by mangecoeur** [apcshields/autocomplete-bibtex#67]
When i was fixing #65 I realized the current release is pretty old compared to master - perhaps a new release is in order? ;)

**Comment by apcshields** [comment]
mangecoeur,

I agree, but I haven't wanted to make a new release until I've had time to test all the changes, and I've had very little spare time at all.

I've added you as a project collaborator. If you would like to let me know when a new release is ready, I can update the package entry in apm.

Thanks,
Andrew

**Comment by mangecoeur** [comment]
Cool beans! I've been using the master branch locally for a while and it seems pretty stable, will try to root out any corner cases. Cheers!

**Comment by mangecoeur** [comment]
Hi @apcshields , I think the current master is stable enough for regular use - go ahead and publish a new version to apm!

**Comment by apcshields** [comment]
Thanks, @mangecoeur!

I've published it as v0.7.0.

**Comment by mangecoeur** [comment]
👍
