### ISSUE TITLE
Does not work with Atom version 0.174

### ISSUE THREAD

**Issue by tomak-git** [apcshields/autocomplete-bibtex#7]
In a recent new version of Atom, there was an update of API and the package now uses deprecated calls.  Specifically, the error concerns the atom.workspaceView which is no longer available. The whole error message is on the screenshot below.

![deprecation](https://cloud.githubusercontent.com/assets/5860787/5772149/f8d99018-9d4c-11e4-83cf-145e5328abe3.png)

**Comment by tomak-git** [comment]
Okay, I uninstalled and reinstalled the package and it works, but the deprecation issue remains.
Btw, thanks a lot for creating the package in the first place. It makes writing a lot easier!

**Comment by apcshields** [comment]
Tomas,


Thanks for letting me know! I'll work on fixing it this weekend.




Andrew


—

**Comment by tomak-git** [comment]
Cool! Now I know what confused me. When I start Atom, the package does not work right away. I have to disable and re-enable it and only then it works. I'm on fully updated Ubuntu 14.10. with Atom 0.174. Just thought that info could be handy ;)

**Comment by apcshields** [comment]
This is going to require some significant rewriting because of how Atom's APIs have changed in the last handful of updates.

I just want you to know that this will probably take me a week or two. Sorry!

**Comment by tomak-git** [comment]
No problem! The package is still working so it's not really a big deal. But it's good to know that the package will be updated. Thanks!
