### ISSUE TITLE
autocomplete-bibtex disables all other completions

### ISSUE THREAD

**Issue by dustinrb** [apcshields/autocomplete-bibtex#72]
With autocomplete-bibtex enabled all other completions/snippets do not show. For example, in the source.gfm scope, typing 't' should bring up completions for the ToDo and Table snippets, but this doesn't happen with ac-bibtex installed. Disable the plugin or changing the scope option in ac-bibtex to ignore source.gfm fixes this issue.

If ac-bibtex is enabled in a scope with completions that begin with '@' such source.julia, those completions will also be displayed in the list, so I'm guessing this is an issue with how the completions are displayed and not with how they're processed. 

Using Atom 1.12.2, autocomplete-bibtex 0.7.0 on macOS 10.12.1
Prevented completions from latex-completions, language-julia, snippets

**Comment by mspittler** [comment]
I have actually the same issue, while I am wondering whether this is a bug or a feature?

Using Atom 1.18.0 x64 on Win7, autocomplete-bibtex 0.7.0
