### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by flipphillips** [apcshields/autocomplete-bibtex#8]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.activate (/Users/flip/.atom/packages/autocomplete-bibtex/node_modules/autocomplete-plus-minimal/lib/autocomplete.coffee:16:31)
```

**Comment by apcshields** [comment]
Duplicates #7.
