### ISSUE TITLE
Reference file in folder?

### ISSUE THREAD

**Issue by tpoisot** [apcshields/autocomplete-bibtex#81]
`vim-pandoc` has a nice default behavior, where it looks for reference files in the active folder -- this would be really nice to have, since otherwise users with several projects need to maintain the list of reference files

**Comment by mangecoeur** [comment]
One option is to use project-manager to set the bibtex variable for the current project (doesn't fix everything but might be good to add it to the docs)

**Comment by tpoisot** [comment]
That'll do as a temporary fix, thanks for the suggestion.

**Comment by mangecoeur** [comment]
closing in favour of #25
