### ISSUE TITLE
Incompatible with autocomplete-latex

### ISSUE THREAD

**Issue by leobrowning92** [apcshields/autocomplete-bibtex#83]
When I enable both autocomplete-latex and autocomplete-bibtex only the bibtex autocomplete functions in a tex file.

Clarification: when typing `@b` , which is the way to prompt for the bibtex autocomplete, it will prompt for `\begin{env}  ...  \end{env}` , as well as the bibtex prompt for papers with authors starting with b. If I type `beg` there is no prompt for `\begin{env}  ...  \end{env}` which would be the standard behaviour for just latex-autocomplete

Can someone please suggest how I can debug this or how I can provide more information for this issue so that it can be resolved?

**Comment by mangecoeur** [comment]
@leobrowning92 the best would be if you could record a short screencast showing the behaviour, it's a bit hard to understand from just the description. I think latex support in any case needs some work (I could probably make it so the autocomplete gets triggered on a custom prefix).
