### ISSUE TITLE
Feature Request: Search more fields

### ISSUE THREAD

**Issue by NoxMortem** [apcshields/autocomplete-bibtex#86]
It looks like only the author and title are searched but this plugin would be extremly more helpful if it could search more fields (like key, abstract, etc.). Very often I want to autocomplete a key, but it only autocompletes if I know the author or I want to pickup a keyword and do not remember the exact title anymore.

    @techreport{Ablub2123,
    timestamp = {2017-11-05T16:31:38Z},
    title = {Blub 2123},
    abstract = {xxxyyyyzzzz},
    author = {A, Blub}
    }

Is not found with @Ablub but only with Blub and not with @xxx either.

**Comment by mangecoeur** [comment]
The latest version in the master development branch now searches on key, title, and authors - but it needs testing so if you can try the dev version that would be great.

**Comment by NoxMortem** [comment]
I downloaded 0.7.1 from the release -> future tags and decompressed into ~\.atom\packages\autocomplete-bibtex.

I hope this was the right way to update to the master development version. It looks like it is searching the said fields, which easens my work a lot.
