### ISSUE TITLE
Convert codebase to ES6

### ISSUE THREAD

**Issue by mangecoeur** [apcshields/autocomplete-bibtex#87]
@apcshields after a bit of a hiatus I'm looking to start updating again, I was wondering how you felt about converting to codebase from coffeescript to ES6 using [decaffeinate](http://decaffeinate-project.org) - I've done this for my other projects since coffeescript seems to be less active, and it makes it possible to write in standard-ish JS.

**Comment by apcshields** [comment]
mangecoeur,

That’s fine with me. I haven’t had time to keep up with the project or changes in Atom or the autocomplete package, and I don’t foresee time to do that in the near future. Whatever works for you is therefore probably best for the active users of the package.

I’m glad to see you’ve had some time lately to work on it!

Andrew

**Comment by mangecoeur** [comment]
Great!

**Comment by tpoisot** [comment]
I think it would be great.

One thing that would be really useful is maybe to fix #81 -- this would allow to look for reference files in the folder.

Another thing would be to reload files on change, as some reference managers auto-export collections on change -- better than having to reload atom.

I can try working on these when the code is converted.

**Comment by mangecoeur** [comment]
> Another thing would be to reload files on change, as some reference managers auto-export collections on change -- better than having to reload atom.

Sure it would be nice if this worked - it actually should already (file watchers are registered on startup that should trigger a reload if any of them change) but for some reason it just doesn't

**Comment by mangecoeur** [comment]
done
