### ISSUE TITLE
Installing this breaks default autocomplete in markdown

### ISSUE THREAD

**Issue by werunom** [apcshields/autocomplete-bibtex#90]
Installing this package breaks the general autocomplete in markdown files. Autocomplete-plus works fine in other scopes (for instance, in tex files, nothing changes). But after uninstalling this package, the general autocomplete-plus starts working again.

And this is not something new - have attempted to use this package before; but everytime I face the same issue. I thought the problem might be because this package hasnt been updated recently. But recently got to know that the package has been in active development in the master-branch. But even if I install this version, the same result. 

Any suggestion why this might be?

Currently using 1.22.1 (64 bit) in Manjaro.

**Comment by mangecoeur** [comment]
Can you specify a bit more in what way this breaks autocomplete-plus? Do you see completions from the bibtex package (these are provided via autocomplete plus)? It could be that bibtex completions are overriding default completions.

**Comment by werunom** [comment]
Excuse! I know I am supposed to give more information; but was bit clueless what I can provide that might help in this investigation. 

1. First of all, I did not try the development edition. So, I still have not followed what mbroedl suggested [here](https://github.com/apcshields/autocomplete-bibtex/issues/85#issuecomment-345226970). Instead, I ran the command - `apm install https://github.com/apcshields/autocomplete-bibtex.git` thinking that all the latest changes are in the master branch.
2. After installing this, I am not getting any autocomplete suggestions in text files (which have markdown scope). Here, I am not getting neither the general autocomplete suggestions nor the bibtex suggestions (after typing '@'). I have set the path for the bibtex file properly and have double checked that. 
3. During this time, autocomplete works fine in other scopes like latex. 
4. I uninstalled autocomplete-bibtex, and general autocomplete starts working fine in text files. 

Let me know what else I can provide regarding this. Thanks for your help!

**Comment by mangecoeur** [comment]
Are you able to provide your bibliography file in some form, perhaps there is the problem. Meanwhile, I suggest you try the development version - if the new version works perhaps your problem is already fixed.

**Comment by werunom** [comment]
I am uploading the bib file (generated through zotero; synced through [better-bibtex](https://github.com/retorquere/zotero-better-bibtex)). I have renamed the extension as pdf because github was not allowing to upload this file. 

[Bibliographies.pdf](https://github.com/apcshields/autocomplete-bibtex/files/1482599/Bibliographies.pdf)

I will try the dev version soon. Have not done this before. In dev mode, would my other packages work fine? 

Let me know if you want any other info...

**Comment by mangecoeur** [comment]
> In dev mode, would my other packages work fine?
Yes they should be fine, the dev-mode package should just override the normal mode package, when you go back to normal mode the dev-mode packages will be ignored.
I will have a look at the bibliography file – I made a lot of changes recently to the file parsing so maybe the dev version will fix your issues.


Sent from Mail for Windows 10

**Comment by werunom** [comment]
Installed and tried the dev version. No luck :( 

Not sure what part of my settings conflicts with this package. Do you want me to share my config.cson? Let me know will that help.

**Comment by mangecoeur** [comment]
OK well your bib file works for me. Lets see your config.cson, maybe it's a problem in there?

**Comment by werunom** [comment]
Below is my config.cson. 
```
"*":
  "Sublime-Style-Column-Selection":
    selectKeyTrigger: "Ctrl"
  "atom-minimap-titles":
    borderOn: false
    font: "ANSI Shadow"
  "autocomplete-bibtex":
    references: [
      "/home/Research/Notes/Bibliographies.bib"
    ]
  "autocomplete-plus":
    backspaceTriggersAutocomplete: true
    enableExtendedUnicodeSupport: true
  "block-cursor":
    global:
      blinkOn:
        backgroundColor: "rgba(31, 173, 121, 0.6)"
        borderColor: "rgba(0, 0, 0, 0)"
        borderStyle: "bordered-box"
    "one-dark-syntax":
      blinkOn:
        backgroundColor: "rgba(31, 173, 121, 0.6)"
        borderColor: "rgba(0, 0, 0, 0)"
        borderStyle: "bordered-box"
      selector: ".theme-one-dark-syntax atom-text-editor"
    "one-light-syntax":
      blinkOn:
        backgroundColor: "rgba(31, 173, 121, 0.6)"
        borderColor: "rgba(0, 0, 0, 0)"
        borderStyle: "bordered-box"
      selector: ".theme-one-light-syntax atom-text-editor"
  "bracket-matcher":
    highlightMatchingLineNumber: true
  core:
    autoHideMenuBar: true
    customFileTypes:
      "source.gfm": [
        "txt"
      ]
    disabledPackages: [
      "wrap-guide"
      "open-on-github"
      "autocomplete-css"
      "autocomplete-html"
      "grammar-selector"
      "language-c"
      "language-clojure"
      "language-coffee-script"
      "language-csharp"
      "language-css"
      "language-git"
      "language-go"
      "language-html"
      "language-hyperlink"
      "language-java"
      "language-javascript"
      "language-json"
      "language-make"
      "language-mustache"
      "language-objective-c"
      "language-perl"
      "language-php"
      "language-property-list"
      "language-python"
      "language-ruby"
      "language-ruby-on-rails"
      "language-sass"
      "language-source"
      "language-shellscript"
      "language-sql"
      "language-toml"
      "language-yaml"
      "language-xml"
      "git-diff"
      "archive-view"
      "autocomplete-atom-api"
      "background-tips"
      "language-typescript"
      "markdown-preview"
      "package-generator"
      "welcome"
    ]
    excludeVcsIgnoredPaths: false
    telemetryConsent: "limited"
    themes: [
      "one-light-ui"
      "one-light-syntax"
    ]
  editor:
    fontFamily: "Fira Code"
    fontSize: 13
    showIndentGuide: true
    softWrap: true
    tabLength: 4
    tabType: "soft"
  "exception-reporting":
    userId: "1156480d-b10f-40b1-aaf3-7a74c0cb38d4"
  "file-icons":
    onChanges: true
    strategies:
      hashbangs: false
      modelines: false
  fonts:
    fontFamily: "FiraCode"
  "git-diff": {}
  "git-plus":
    general: {}
  "grammar-token-limit":
    maxTokensPerLine: 150
  "highlight-line":
    enableBackgroundColor: false
    enableUnderline: true
    underline: "dotted"
  "highlight-selected":
    highlightBackground: true
  latex:
    opener: "custom"
    outputDirectory: "/home/varun/latexOutput"
    viewerPath: "/usr/bin/masterpdfeditor4"
  "latex-completions": {}
  latexer:
    parameters_to_search_citations_by: [
      "author"
      "year"
    ]
  "markdown-preview-enhanced":
    closePreviewAutomatically: false
    fileExtension: ".md, .mmark, .markdown, .txt"
    openPreviewPaneAutomatically: false
  "markdown-table-formatter":
    defaultTableJustification: "Center"
  "markdown-writer":
    lineStyles:
      h1:
        before: "# "
      h2:
        before: "## "
      h3:
        before: "### "
      h4:
        before: "#### "
      h5:
        before: "##### "
      h6:
        before: "###### "
      ol:
        before: "1. "
        regexBefore: "(?:-|\\*|\\+|\\.|\\d+[\\.\\)]|[a-zA-Z]+[\\.\\)])\\s"
        regexMatchBefore: "(?:\\d+[\\.\\)]|[a-zA-Z]+[\\.\\)])\\s"
    orderedNewLineNumberContinuation: false
    templateVariables:
      ulBullet0: "+"
      ulBullet1: "*"
      ulBullet2: "+"
      ulBullet3: "*"
  minimap:
    displayPluginsControls: false
    plugins:
      cursorline: true
      cursorlineDecorationsZIndex: 0
      "highlight-selected": true
      "highlight-selectedDecorationsZIndex": 0
  "spell-check":
    grammars: [
      "source.asciidoc"
      "source.gfm"
      "text.git-commit"
      "text.plain"
      "text.plain.null-grammar"
      "text.tex.latex"
    ]
  "symbols-tree-view": {}
  tabs:
    enableMruTabSwitching: false
  welcome:
    showOnStartup: false
  wordcount:
    alwaysOn: true
    hidechars: true


```

**Comment by werunom** [comment]
Also, I wanted to point you to [this issue](https://github.com/atom/autocomplete-plus/issues/824) in autocomplete-plus package. Seems to be very similar in nature, but with a slight variation - autocomplete-plus does not work only when I install autocomplete-bibtex. 

Thought might be of some relevance.

**Comment by werunom** [comment]
Hey....did you have time to go through the config.cson?

**Comment by mangecoeur** [comment]
TBH I can't see anything wrong in your config either. Maybe try disabling other markdown-related packages (e.g. markdown writer) in case there is some weird interaction there. I've not seen any similar issues, so I don't think this is an issue with autocomplete-bibtex itself, but maybe some interaction between other packages. 

Or, you can try running Atom in dev-mode and opening the console view and seeing if any errors are reported there (although packages often tend to use 'catch-all' error handlers which make it harder to catch bugs). 

Finally, I would suggest clean-reinstalling atom and your packages (remove atom, remove all config and installed packages, then reinstall bit-by-bit) and seeing if that cures your issue.

**Comment by dlmiyamoto** [comment]
I can verify that `autocomplete-bibtex` is breaking autocomplete-plus in `source.gfm` files. When  `autocomplete-bibtex` is disabled, `autocomplete-plus` suggestions for snippets appear. When it's enabled, they do not but will expand on Tab.

**Comment by rriemann** [comment]
One of the forks has a patch that may help here as well:

https://github.com/tpoisot/autocomplete-citeproc/commit/06c00bcd927b8fe30ee51882b54fb518c60341e8

**Comment by werunom** [comment]
@mangecoeur - requesting to look into this :) Has been without autocomplete support for markdown for long. Getting this to work, would make writing far more easier than present. Thanks!

**Comment by mbroedl** [comment]
@werunom I used to have the same issues (but never really bothered about it because I only ever use citations in markdown) but it seems gone now after updating my system. Maybe that helps?

Atom 1.23.3
autocomplete-plus 2.40.0
autocomplete-bibtex 1.1.0

**Comment by werunom** [comment]
@mbroedl - thanks for informing. Will try that now...

@mbroedl or @mangecoeur - I need help with installing this package. I followed the below steps

1. Downloaded the zip file of this package from `master` branch.
2. Unzipped into a folder and ran the command `apm install`

The isntall command ran fine. But when I restarted the atom, I dont see the package ☹️ . I tried starting atom in `dev` mode too; but I dont see the package. 

What more should I have done to install the package fine?

**Comment by werunom** [comment]
Okay. Got it working by just extracting the zip folder and running `apm link` command. 

but now, I am facing the below problem! 
```
Error: Cannot find module 'fs-extra'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/varun/Downloads/autocomplete-bibtex-master/lib/provider.js:3:12)
    at Object.<anonymous> (/home/varun/Downloads/autocomplete-bibtex-master/lib/provider.js:223:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/varun/Downloads/autocomplete-bibtex-master/lib/main.js:6:27)
    at Object.<anonymous> (/home/varun/Downloads/autocomplete-bibtex-master/lib/main.js:100:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:937:35)
    at /usr/share/atom/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
```

**Comment by mbroedl** [comment]
Actually, for me it works with the current stable release in atom itself (to download via Settings -> Updates -> and then update everything).
What you may want to try in case you want to proceed with your error: go into the autocomplete-bibtex-master folder and type `npm install` that should update all your dependencies, which this error seems to be hinting at.

**Comment by KevCaz** [comment]
Similar issue here even with the latest versions: 

Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
autocomplete-plus 2.40.0
autocomplete-bibtex 1.1.0
working on Debian 9. 

I've therefore checked what's going on and found that when I disable AutocompleteBibtex everything works fine. I have also noticed that the autocompletion works normally in scope `comment.quote.gfm` (i.e. when I use `>` in markdown files) even when AutcompleteBibtex is enabled. 

Anyway, I'll keep a close eye on this issue and many thanks for the work on the package 😄 .

**Comment by KevCaz** [comment]
A short follow-up: I no longer experience this issue since version 1.2.0.
Many thanks. :)

**Comment by werunom** [comment]
@KevCaz  - thanks for pointing. Installed and tried - and it works fine!!

@mangecoeur - thanks for the update!
