### ISSUE TITLE
autocomplete-latex-cite

### ISSUE THREAD

**Issue by tpoisot** [apcshields/autocomplete-bibtex#91]
See this package: https://github.com/hesstobi/atom-autocomplete-latex-cite

It has (1) auto-reload and (2) search from local files

**Comment by mangecoeur** [comment]
I would welcome a PR merging this functionality into autocomplete bibtex.

**Comment by tpoisot** [comment]
I'm looking into how feasible this is.

**Comment by mangecoeur** [comment]
@tpoisot auto reload is now implemented
