### ISSUE TITLE
Does not recognize capitalized field names?

### ISSUE THREAD

**Issue by robertsck** [apcshields/autocomplete-bibtex#94]
It appears as though autocomplete-bibtex does not recognize BibTex fields if the field name is capitalized. If I do a Bibliography search, it only displays the cite key, the rest of the entry contains simply a "--".  Attempting autocomplete will also only display the cite key with "  "undefined",.  " in the description section. All displays as expected for an entry if I edit the .bib file such that the field names are lower case. Unfortunately, I use BibDesk which likes to capitalize field names. Is this expected behavior?

**Comment by mangecoeur** [comment]
could you post samples of working and non-working bibtext files (preferably really short with just a couple of entries) so I can resolve this and add it to the test suite?

**Comment by mangecoeur** [comment]
should be fine in latest release
